export interface Rictionary {
    RictionaryId: number;
    RictionaryName: string;
    CreatedDate: string | Date;
    LastModifiedDate: string | Date;
    CreatedBy: string;
    LastModifiedBy: string;
    AValue: string;
    BValue: string;
    CValue: string;
    DValue: string;
    EValue: string;
    FValue: string;
    GValue: string;
    HValue: string;
    IValue: string;
    JValue: string;
    KValue: string;
    LValue: string;
    MValue: string;
    NValue: string;
    OValue: string;
    PValue: string;
    QValue: string;
    RValue: string;
    SValue: string;
    TValue: string;
    UValue: string;
    VValue: string;
    WValue: string;
    XValue: string;
    YValue: string;
    ZValue: string;
    [key: string]: string | number | Date;
}
